export const FEATURES = [
  {
    id: 'productos',
    name: 'Productos',
    desc: 'Menú de productos con precios',
    icon: '🍕',
    plan: 'free',
    defaultOn: true,
  },
  {
    id: 'pedidos',
    name: 'Pedidos',
    desc: 'Recepción de pedidos por chat',
    icon: '🛵',
    plan: 'free',
    defaultOn: true,
  },
  {
    id: 'horario',
    name: 'Horarios',
    desc: 'Horarios de atención',
    icon: '🕐',
    plan: 'free',
    defaultOn: true,
  },
  {
    id: 'contacto',
    name: 'Contacto',
    desc: 'Información de contacto',
    icon: '📞',
    plan: 'free',
    defaultOn: true,
  },
  {
    id: 'catalogo_visual',
    name: 'Catálogo visual',
    desc: 'Envía imágenes de productos en el menú',
    icon: '🖼️',
    plan: 'premium',
    defaultOn: false,
  },
  {
    id: 'cupones',
    name: 'Cupones / Descuentos',
    desc: 'Códigos de descuento para clientes',
    icon: '🏷️',
    plan: 'premium',
    defaultOn: false,
  },
  {
    id: 'recordatorios',
    name: 'Recordatorios',
    desc: 'Envía recordatorios automáticos a clientes',
    icon: '⏰',
    plan: 'premium',
    defaultOn: false,
  },
  {
    id: 'fuera_horario',
    name: 'Respuesta fuera de horario',
    desc: 'Auto-respuesta cuando el bot está fuera del horario configurado',
    icon: '🌙',
    plan: 'premium',
    defaultOn: false,
  },
  {
    id: 'chatbot_ia',
    name: 'Chatbot IA',
    desc: 'Respuestas inteligentes con IA para consultas avanzadas',
    icon: '🤖',
    plan: 'unlimited',
    defaultOn: false,
  },
  {
    id: 'stats_semanal',
    name: 'Estadísticas semanales',
    desc: 'Recibe un resumen semanal de actividad del bot',
    icon: '📊',
    plan: 'premium',
    defaultOn: false,
  },
]
