export const THEMES = [
  {
    id: 'classic',
    name: 'Clásico',
    desc: '🕊️ Paloma · separadores ━━━ · estilo original',
    headerIcon: '🕊️',
    separator: '━━━━━━━━━━━━━━',
    bullet: '•',
    titlePrefix: '🍕',
    titleSuffix: '🍕',
    accentEmoji: '💬',
    productBullet: '•',
    productConnector: '—',
    orderReceiptIcon: '✅',
    orderNoteIcon: '🔔',
    scheduleIcon: '🕐',
    contactIcon: '📍',
    borderChar: null,
  },
  {
    id: 'modern',
    name: 'Moderno',
    desc: '◇ Rombo · separadores ─── · estilo profesional',
    headerIcon: '◇',
    separator: '────────────────',
    bullet: '›',
    titlePrefix: '▸',
    titleSuffix: '',
    accentEmoji: '📱',
    productBullet: '›',
    productConnector: '→',
    orderReceiptIcon: '✔️',
    orderNoteIcon: '📬',
    scheduleIcon: '⏰',
    contactIcon: '📞',
    borderChar: null,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    desc: '── Sin íconos · solo texto funcional',
    headerIcon: '',
    separator: '───',
    bullet: '-',
    titlePrefix: '',
    titleSuffix: '',
    accentEmoji: '',
    productBullet: '-',
    productConnector: ':',
    orderReceiptIcon: '[OK]',
    orderNoteIcon: '[i]',
    scheduleIcon: '',
    contactIcon: '',
    borderChar: null,
  },
  {
    id: 'bold',
    name: 'Osado',
    desc: '★彡 Estrella fugaz · separadores ████ · llamativo',
    headerIcon: '★彡',
    separator: '████████████████',
    bullet: '◆',
    titlePrefix: '🔥',
    titleSuffix: '🔥',
    accentEmoji: '📞',
    productBullet: '◆',
    productConnector: '➜',
    orderReceiptIcon: '✅',
    orderNoteIcon: '🔊',
    scheduleIcon: '⏳',
    contactIcon: '📍',
    borderChar: '█',
  },
  {
    id: 'elegant',
    name: 'Elegante',
    desc: '✦ Estrella · separadores ═══ · estilo fino',
    headerIcon: '✦',
    separator: '════════════════',
    bullet: '⟡',
    titlePrefix: '✦',
    titleSuffix: '✦',
    accentEmoji: '✉️',
    productBullet: '⟡',
    productConnector: '→',
    orderReceiptIcon: '✓',
    orderNoteIcon: '✉',
    scheduleIcon: '🕘',
    contactIcon: '✉',
    borderChar: '═',
  },
  {
    id: 'ocean',
    name: 'Oceano',
    desc: '🌊 Olas · separadores ~~~~~~~~ · vibra marina',
    headerIcon: '🌊',
    separator: '~~~~~~~~~~~~~~~~',
    bullet: '・',
    titlePrefix: '🌊',
    titleSuffix: '',
    accentEmoji: '💙',
    productBullet: '・',
    productConnector: '→',
    orderReceiptIcon: '✅',
    orderNoteIcon: '📬',
    scheduleIcon: '⏰',
    contactIcon: '📍',
    borderChar: null,
  },
  {
    id: 'sunset',
    name: 'Atardecer',
    desc: '🌅 Sol · separadores ☼☼☼☼☼☼☼ · tonos cálidos',
    headerIcon: '🌅',
    separator: '☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼☼',
    bullet: '☼',
    titlePrefix: '☀️',
    titleSuffix: '',
    accentEmoji: '🌇',
    productBullet: '☼',
    productConnector: '→',
    orderReceiptIcon: '✔️',
    orderNoteIcon: '✉️',
    scheduleIcon: '⏳',
    contactIcon: '📞',
    borderChar: null,
  },
  {
    id: 'neon',
    name: 'Neón',
    desc: '💜 Purple · separadores ▬▬▬ · estilo cyberpunk',
    headerIcon: '💜',
    separator: '▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬',
    bullet: '✦',
    titlePrefix: '⚡',
    titleSuffix: '⚡',
    accentEmoji: '📱',
    productBullet: '✦',
    productConnector: '➤',
    orderReceiptIcon: '✅',
    orderNoteIcon: '🔊',
    scheduleIcon: '⏳',
    contactIcon: '📍',
    borderChar: '▬',
  },
  {
    id: 'nature',
    name: 'Naturaleza',
    desc: '🌿 Hoja · separadores ┈┈┈┈ · estilo orgánico',
    headerIcon: '🌿',
    separator: '┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈',
    bullet: '•',
    titlePrefix: '🌱',
    titleSuffix: '🌱',
    accentEmoji: '💚',
    productBullet: '•',
    productConnector: '→',
    orderReceiptIcon: '✅',
    orderNoteIcon: '💌',
    scheduleIcon: '⏰',
    contactIcon: '📞',
    borderChar: null,
  },
  {
    id: 'royal',
    name: 'Real',
    desc: '👑 Corona · separadores ═══✧═══ · estilo lujo',
    headerIcon: '👑',
    separator: '══════✧══════',
    bullet: '✦',
    titlePrefix: '✨',
    titleSuffix: '✨',
    accentEmoji: '💎',
    productBullet: '✦',
    productConnector: '➜',
    orderReceiptIcon: '✓',
    orderNoteIcon: '✉',
    scheduleIcon: '🕰️',
    contactIcon: '✉',
    borderChar: '═',
  },
]

export function getThemeList() {
  return THEMES.map(t => ({ id: t.id, name: t.name, desc: t.desc, headerIcon: t.headerIcon }))
}
